included:
  - ios/Sources
  - ios/Tests

excluded:
  - ios/.generated

analyzer_rules:
  - unused_declaration
  - unused_import

opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_count
  - empty_string
  - explicit_init
  - fallthrough
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - implicitly_unwrapped_optional
  - last_where
  - legacy_multiple
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - private_action
  - private_outlet
  - prohibited_super_call
  - reduce_boolean
  - sorted_first_last
  - toggle_bool
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - yoda_condition

disabled_rules:
  - todo

force_cast: error
force_try: error
force_unwrapping: error
trailing_comma:
  mandatory_comma: true
line_length:
  warning: 120
  error: 140
type_body_length:
  warning: 750
  error: 800
file_length:
  warning: 750
  error: 800
function_body_length:
  warning: 50
  error: 70
identifier_name:
  min_length: 2
  excluded:
    - id
reporter: xcode
