#!/usr/bin/env bash
set -euo pipefail

REPOSITORY_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG_DIR="$REPOSITORY_ROOT/ios/Configurations"
CONFIG_FILE="$CONFIG_DIR/Local.xcconfig"

escape_xcconfig_url() {
  local raw="$1"
  if [[ -z "$raw" ]]; then
    echo ""
    return 0
  fi
  # Normalize any existing :/$()/ or multiple slashes to standard ://
  local normalized
  normalized="$(printf '%s' "$raw" | sed -E 's|:/\$\(\)/|://|g; s|://+|://|g')"
  # Escape :// to :/$()/ for xcconfig to prevent Xcode treating // as comment delimiter
  printf '%s' "$normalized" | sed 's|://|:/$()/|g'
}

# Determine if any provisioning variables are present in the environment
HAS_ENV_CONFIG=false
if [[ -n "${SPC_SUPABASE_PUBLISHABLE_KEY:-}" ]] || [[ -n "${SPC_OAUTH_REDIRECT_URL:-}" ]] || [[ -n "${SPC_SUPABASE_URL:-}" ]]; then
  HAS_ENV_CONFIG=true
fi

if [[ "$HAS_ENV_CONFIG" == "true" ]]; then
  mkdir -p "$CONFIG_DIR"
  TMP_FILE="$(mktemp "$CONFIG_DIR/Local.xcconfig.tmp.XXXXXX")"

  REDIRECT_URL="${SPC_OAUTH_REDIRECT_URL:-spc://auth/callback}"
  ESCAPED_REDIRECT="$(escape_xcconfig_url "$REDIRECT_URL")"

  {
    echo "// Generated by scripts/provision_local_xcconfig.sh - DO NOT COMMIT"
    echo "// See docs/phase-1c/AUTH_CONFIG_PROVISIONING.md for details."
    if [[ -n "${SPC_PUBLIC_API_BASE_URL:-}" ]]; then
      echo "SPC_PUBLIC_API_BASE_URL = $(escape_xcconfig_url "$SPC_PUBLIC_API_BASE_URL")"
    fi
    if [[ -n "${SPC_ALLOWED_API_HOSTS:-}" ]]; then
      echo "SPC_ALLOWED_API_HOSTS = $SPC_ALLOWED_API_HOSTS"
    fi
    if [[ -n "${SPC_PRODUCTION_API_HOSTS:-}" ]]; then
      echo "SPC_PRODUCTION_API_HOSTS = $SPC_PRODUCTION_API_HOSTS"
    fi
    if [[ -n "${SPC_AUDIO_CATALOG_MANIFEST_URL:-}" ]]; then
      echo "SPC_AUDIO_CATALOG_MANIFEST_URL = $(escape_xcconfig_url "$SPC_AUDIO_CATALOG_MANIFEST_URL")"
    fi
    if [[ -n "${SPC_AUDIO_CATALOG_AUTHORIZATION_URL:-}" ]]; then
      echo "SPC_AUDIO_CATALOG_AUTHORIZATION_URL = $(escape_xcconfig_url "$SPC_AUDIO_CATALOG_AUTHORIZATION_URL")"
    fi
    if [[ -n "${SPC_AUDIO_CATALOG_ALLOWED_HOSTS:-}" ]]; then
      echo "SPC_AUDIO_CATALOG_ALLOWED_HOSTS = $SPC_AUDIO_CATALOG_ALLOWED_HOSTS"
    fi

    if [[ -n "${SPC_SUPABASE_URL:-}" ]]; then
      echo "SPC_SUPABASE_URL = $(escape_xcconfig_url "$SPC_SUPABASE_URL")"
    fi

    if [[ -n "${SPC_SUPABASE_PUBLISHABLE_KEY:-}" ]]; then
      echo "SPC_SUPABASE_PUBLISHABLE_KEY = $SPC_SUPABASE_PUBLISHABLE_KEY"
    else
      echo "SPC_SUPABASE_PUBLISHABLE_KEY ="
    fi

    echo "SPC_OAUTH_REDIRECT_URL = $ESCAPED_REDIRECT"
  } > "$TMP_FILE"

  chmod 600 "$TMP_FILE" 2>/dev/null || true
  mv -f "$TMP_FILE" "$CONFIG_FILE"
  echo "Provisioned ios/Configurations/Local.xcconfig from environment variables."
elif [[ -f "$CONFIG_FILE" ]]; then
  echo "Preserving existing ios/Configurations/Local.xcconfig."
else
  echo "Notice: No environment variables provided and Local.xcconfig absent; skipping provisioning."
fi
